"""
Report Builder — maps DB judgements to the frontend citation format.
Uses Gemini to enrich ANY blank fields (ratio, court, date, statutes, excerpt, coram)
from raw_content so the report is NEVER empty/blank.
"""

from __future__ import annotations

import json
import logging
import os
import re
import uuid
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


# Target citation points so report has exactly this many sections
TARGET_CITATION_POINTS = 10

_SOURCE_LABELS = {
    "local":         "Local DB",
    "indian_kanoon": "Indian Kanoon",
    "google":        "Google Search",
    "citation_agent":"AI Generated",
}

# Human-readable "where this case was fetched from" for report display
_SOURCE_FETCHED_FROM = {
    "local":         "This relevant case was fetched from: Local Database (previously indexed judgments).",
    "indian_kanoon": "This relevant case was fetched from: Indian Kanoon (indiankanoon.org).",
    "google":        "This relevant case was fetched from: Google Search (web).",
    "citation_agent":"This citation was generated by AI (no external fetch).",
}

_AUDIT_TO_STATUS = {
    "VERIFIED":               "GREEN",
    "VERIFIED_WITH_WARNINGS": "GREEN",
    "NEEDS_REVIEW":           "YELLOW",
    "QUARANTINED":            "RED",
}

def _derive_failure_reason(j: Dict[str, Any], audit_info: Optional[Dict[str, Any]], v: Dict[str, Any]) -> str:
    """
    Produce a human-readable reason for RED / PENDING citations.
    Priority: overruled > hallucination flag > layer fail > low score > generic.
    """
    # Confirmed overruled by subsequent treatment extraction
    st = j.get("subsequent_treatment") or {}
    overruled = st.get("overruled") or []
    if overruled:
        by = "; ".join(str(x) for x in overruled[:2])
        return f"Confirmed overruled by: {by}"

    # Auditor hallucination flags
    flags = (audit_info or {}).get("hallucination_flags") or []
    if "future_year_in_citation" in flags:
        return "Citation contains a future year — likely hallucinated"
    if "placeholder_citation" in flags:
        return "Citation string is a placeholder or template value (e.g. '—', 'N/A')"
    if "suspiciously_simple_citation" in flags:
        return "Citation format is suspiciously simple and may not refer to a real judgment"

    # Trace-based reasons
    trace = v.get("trace") or []
    for t in trace:
        if "L1:FAIL" in t:
            return "Not found in any verified source — citation does not exist in our database or Indian Kanoon"
        if "L3:FAIL" in t:
            score = v.get("match_score", 0)
            return f"Proposition misalignment — what this case says does not match how it was cited (match score: {score}%)"
        if "AUDITOR:QUARANTINED" in t:
            return "Flagged by automated verification — citation could not be confirmed in authoritative sources"

    # Confidence too low
    score = v.get("match_score", 0)
    if score < 50:
        return f"Insufficient confidence ({score}%) — citation could not be verified through available sources"

    return "Verification failed — manual review required before use in court submissions"


def _compute_priority_score(j: Dict[str, Any], audit_info: Optional[Dict[str, Any]], query_volume: int = 1) -> float:
    """
    Compute HITL priority score 0.0–1.0 for queue ordering.
    Higher score → shorter SLA:
      >= 0.85 → 4 hours (URGENT)
      0.70–0.84 → 8 hours (Standard)
      0.50–0.69 → 24 hours (Normal)
      < 0.50 → 72 hours (Low)
    """
    score = 0.0
    court = (j.get("court") or "").lower()
    if "supreme court" in court:
        score += 0.4
    elif "high court" in court:
        score += 0.25
    elif "district" in court or "sessions" in court:
        score += 0.05
    else:
        score += 0.15

    year = j.get("year") or 0
    try:
        year = int(year)
    except (TypeError, ValueError):
        year = 0
    current_year = datetime.utcnow().year
    recency = max(0, 1.0 - (current_year - year) / 30.0) if year else 0
    score += recency * 0.3

    # Query volume bonus (more users queried → higher priority)
    vol_bonus = min(0.2, query_volume * 0.02)
    score += vol_bonus

    # Confidence bonus: very low confidence = less urgent (likely junk)
    conf = (audit_info or {}).get("final_confidence") or j.get("audit_confidence") or 0
    try:
        conf = int(conf)
    except (TypeError, ValueError):
        conf = 0
    if conf > 40:
        score += 0.1

    return round(min(1.0, score), 3)

def _strip_html(text: str) -> str:
    if not text:
        return ""
    text = re.sub(r"<script[^>]*>.*?</script>", " ", text, flags=re.I | re.S)
    text = re.sub(r"<style[^>]*>.*?</style>", " ", text, flags=re.I | re.S)
    text = re.sub(r"<[^>]+>", " ", text)
    return text


def _looks_like_css(text: str) -> bool:
    if not text:
        return False
    sample = text[:8000]
    css_tokens = sum(sample.count(tok) for tok in ("{", "}", ";", ":", "var(--", "font-", "background", "border", "@keyframes"))
    return css_tokens >= 12


def _clean_excerpt(text: str) -> str:
    if not text:
        return ""
    text = _strip_html(text)
    # Remove inline CSS blocks or style rules
    text = re.sub(r"\{[^}]{0,800}\}", " ", text)
    # Collapse whitespace
    text = re.sub(r"\s+", " ", text).strip()
    # If still looks like CSS or boilerplate, discard
    if _looks_like_css(text):
        return ""
    return text


def _strip_html_css(text: str) -> str:
    """
    Remove HTML tags and CSS/stylesheet content so SOURCE EXCERPT shows only judgment prose.
    If the excerpt looks like CSS (e.g. .class { ... } or var(--...) ), return cleaned text or empty.
    """
    if not text or not isinstance(text, str):
        return (text or "").strip()
    # Strip HTML tags
    out = re.sub(r"<[^>]+>", " ", text)
    out = re.sub(r"\s+", " ", out).strip()
    # Drop lines that are predominantly CSS (selectors, rules, var(--), etc.)
    lines = [ln.strip() for ln in out.split("\n") if ln.strip()]
    kept = []
    for ln in lines:
        # Skip lines that look like CSS
        if re.search(r"^\s*[.#\w\[\]]+\s*\{", ln) or "var(--" in ln or "}\s*;" in ln:
            continue
        if re.search(r"\b(px|em|rem|%)?\s*;?\s*}\s*$", ln) and re.search(r"[{}]", ln):
            continue
        if len(ln) > 20 and (ln.count("{") + ln.count("}") + ln.count(";")) >= 3:
            continue
        kept.append(ln)
    out = "\n".join(kept).strip()
    # If nothing left or still looks like code, try taking only sentence-like segments
    if not out or re.search(r"^\s*[.#]|var\(--|gradient|border-radius|box-shadow", out[:200]):
        # Fallback: take only lines that look like prose (contain spaces, no leading . or #)
        prose_lines = [ln for ln in lines if " " in ln and not re.match(r"^\s*[.#\w-]+\s*\{", ln) and "var(" not in ln]
        out = " ".join(prose_lines).strip() if prose_lines else ""
    return out[:3000] if out else ""


# ─── Gemini enrichment (fills blank fields from raw text) ─────────────────────

# Default prompt kept as fallback for when DB has no row for "ReportBuilder"
_DEFAULT_REPORT_ENRICHMENT_PROMPT = """You are a legal data extraction expert for Indian court judgments.
Extract ALL 10 mandatory citation points from the FULL judgment text below. Read the entire text — ratio and holdings often appear in the middle or end.
Use recognized reporters (SCC, AIR). Do NOT leave any point empty if the information appears in the text. Use "Further research needed" only when genuinely absent.
Return ONLY a JSON object.

10 Required Points (exact keys):
{{
  "caseName": "Exact full case name (Appellant v. Respondent), correct spelling",
  "primaryCitation": "Recognized reporter citation e.g. (2019) 10 SCC 1 or AIR 2020 SC 100",
  "alternateCitations": ["other reporter citations found in document"],
  "court": "Supreme Court of India / High Court of Bombay / etc.",
  "coram": "Judges on bench e.g. Justice D.Y. Chandrachud, Justice A.S. Bopanna",
  "benchType": "Division Bench / 3-Judge Bench / Constitution Bench / Single Judge",
  "dateOfJudgment": "DD Month YYYY",
  "statutes": ["Section 302, Indian Penal Code, 1860", "Article 21, Constitution of India"],
  "ratio": "Ratio decidendi: precise legal principle in 2-4 sentences, from the judgment body",
  "excerptPara": "Pinpoint paragraph e.g. Para 42",
  "excerptText": "Verbatim key paragraph (max 300 words)",
  "subsequentTreatment": {{ "followed": [], "distinguished": [], "overruled": [] }} — if mentioned in text,
  "verificationStatus": "Verified and authentic" | "Requires review" | "Invalid / not found",
  "officialSourceUrl": "Official court/eCourts URL if found, else null"
}}

Case title: {title}
Query context: {query}

Full judgment text (extract all 10 points from this):
{raw}

JSON:"""

def _enrich_with_gemini(j: Dict[str, Any], query: str) -> Dict[str, Any]:
    """
    If any of the 10 citation points are blank or placeholders, call Gemini to extract from full judgment text.
    Goal: zero mistakes — report must show real data from the judgment, not empty or wrong placeholders.
    """
    # Use as much of the full judgment as possible for complete extraction
    raw  = (j.get("raw_content") or j.get("full_text") or j.get("excerpt_text") or "")[:25000].strip()
    title = (j.get("title") or "").strip()

    # Consider placeholders as missing so we try to enrich (all 10 points)
    _blank = ("—", "Further research needed", "Further research needed.", "Ratio not available.", "Court not specified", "Not specified", "Unknown", "Web", "null", "None", "")
    ratio_ok = (j.get("ratio") or "").strip() and (j.get("ratio") or "").strip() not in _blank
    court_ok = (j.get("court") or "").strip() and (j.get("court") or "").strip() not in _blank
    date_ok = (j.get("date_judgment") or "").strip() and (j.get("date_judgment") or "").strip() not in _blank
    coram_ok = (j.get("coram") or "").strip() and (j.get("coram") or "").strip() not in _blank
    citation_ok = (j.get("primary_citation") or "").strip() and (j.get("primary_citation") or "").strip() not in _blank
    needs_enrich = not (ratio_ok and court_ok and date_ok and coram_ok and citation_ok) or not (j.get("statutes") or [])

    if not needs_enrich or not raw:
        return j

    api_key = os.environ.get("GOOGLE_API_KEY") or os.environ.get("GEMINI_API_KEY")
    if not api_key:
        return j

    # Resolve prompt, model, temperature from DB → fallback to defaults
    try:
        from utils.prompt_resolver import resolve_prompt
        pc = resolve_prompt(
            name="ReportBuilder",
            agent_type="citation",
            default_prompt=_DEFAULT_REPORT_ENRICHMENT_PROMPT,
            default_model=os.environ.get("GEMINI_MODEL", "gemini-2.0-flash"),
            default_temperature=0.1,
            default_max_tokens=1024,
        )
        prompt = pc.prompt.format(title=title, query=query, raw=raw)
        model = pc.model_name
        temperature = pc.temperature
        max_tokens = pc.max_tokens
        logger.info("[REPORT_BUILDER] Prompt source=%s model=%s temp=%.2f", pc.source, model, temperature)
    except Exception as exc:
        logger.warning("[REPORT_BUILDER] Prompt resolver failed (%s), using default", exc)
        prompt = _DEFAULT_REPORT_ENRICHMENT_PROMPT.format(title=title, query=query, raw=raw)
        model = os.environ.get("GEMINI_MODEL", "gemini-2.0-flash")
        temperature = 0.1
        max_tokens = 1024

    try:
        from google import genai as _genai
        from google.generativeai import types
        client = _genai.Client(api_key=api_key)

        # Start with safelist config from PromptConfig, merge explicit settings
        config_kw: Dict[str, Any] = pc.gemini_config
        config_kw["responseMimeType"] = "application/json"
        
        config = types.GenerateContentConfig(**config_kw)

        resp   = client.models.generate_content(
            model    = model,
            contents = prompt,
            config   = config,
        )
        text = (resp.text or "").strip()
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"```\s*$", "", text)
        extracted = json.loads(text)

        def _fill(field, key, is_list=False):
            existing = j.get(field)
            if is_list:
                if not existing or existing == ["—"] or existing == []:
                    v = extracted.get(key)
                    if v and isinstance(v, list):
                        j[field] = [str(x).strip() for x in v if x]
                    elif v and isinstance(v, str):
                        j[field] = [v.strip()]
            else:
                if not existing or str(existing).strip() in ("", "—", "null", "None", "Not specified", "Court not specified", "Unknown", "Web"):
                    v = extracted.get(key)
                    if v and str(v).strip() not in ("null", "None", ""):
                        # Don't overwrite with "not found" / "not available" for case name
                        if field == "title" and str(v).strip().lower() in (
                            "case name not found in the provided text.",
                            "not available in the provided text.",
                        ):
                            pass
                        else:
                            j[field] = str(v).strip()

        _fill("title",           "caseName")
        _fill("primary_citation","primaryCitation")
        _fill("court",           "court")
        _fill("coram",           "coram")
        _fill("bench_type",      "benchType")
        _fill("date_judgment",   "dateOfJudgment")
        _fill("ratio",           "ratio")
        _fill("excerpt_para",    "excerptPara")
        _fill("excerpt_text",    "excerptText")
        _fill("alternate_citations", "alternateCitations", is_list=True)
        _fill("statutes",        "statutes", is_list=True)
        if isinstance(extracted.get("subsequentTreatment"), dict):
            st = extracted["subsequentTreatment"]
            if any(st.get(k) for k in ("followed", "distinguished", "overruled")):
                j["subsequent_treatment"] = {
                    "followed": st.get("followed") or [],
                    "distinguished": st.get("distinguished") or [],
                    "overruled": st.get("overruled") or [],
                }
        v = extracted.get("verificationStatus")
        if v and str(v).strip() and str(v).strip().lower() not in ("null", "none"):
            j["verification_status_extracted"] = str(v).strip()
        ourl = extracted.get("officialSourceUrl")
        if ourl and str(ourl).strip() and str(ourl).strip().lower() not in ("null", "none"):
            j["official_source_url"] = str(ourl).strip()

        logger.info("[REPORT_BUILDER/GEMINI] Enriched: %s", (j.get("title") or "")[:60])
    except Exception as e:
        logger.warning("[REPORT_BUILDER/GEMINI] Enrichment failed for '%s': %s", title[:50], e)

    return j


# ─── Three-layer verification helpers (existence, metadata, proposition) ─────

def _court_tier(court: str) -> str:
    court = (court or "").lower()
    if "supreme court" in court:
        return "SC"
    if any(x in court for x in ["delhi high court", "bombay high court", "madras high court"]):
        return "HC_MAJOR"
    if "high court" in court:
        return "HC_OTHER"
    if any(x in court for x in ["district", "sessions"]):
        return "DISTRICT"
    return "OTHER"


def _apply_three_layer_verification(
    j: Dict[str, Any],
    query: str,
    route: str,
    audit_info: Optional[Dict[str, Any]],
) -> Dict[str, Any]:
    """
    Implement:
      Layer 1 — existence (does citation exist in verified storage?)
      Layer 2 — metadata (court + year consistency)
      Layer 3 — proposition alignment (semantic score with court-tier thresholds)

    Returns dict with: status (GREEN/YELLOW/RED), confidence (0–100),
    match_score (0–100), verdict (MATCH/PARTIAL/MISMATCH), trace (list[str]).
    """
    trace: List[str] = []

    # --- Inputs from auditor / DB ---
    audit_status = (audit_info or {}).get("audit_status") or j.get("audit_status")
    base_score = (audit_info or {}).get("final_confidence") or j.get("audit_confidence") or 0
    try:
        base_score = int(base_score or 0)
    except (TypeError, ValueError):
        base_score = 0

    # ── LAYER 1: existence check ─────────────────────────────────────────────
    exists = bool(j.get("primary_citation") or j.get("canonical_id"))
    if not exists:
        trace.append("L1:FAIL — citation not found in verified storage")
        return {
            "status": "RED",
            "confidence": 40,
            "match_score": 40,
            "verdict": "MISMATCH",
            "trace": trace,
        }

    trace.append("L1:PASS — citation exists in verified storage")

    # ── LAYER 2: metadata verification (court + year) ────────────────────────
    court = j.get("court") or j.get("court_code") or ""
    tier = _court_tier(court)
    cited_year = j.get("year_cited")  # optional: could be parsed from citation string upstream
    stored_year = j.get("year")
    layer2_ok = True
    if stored_year and cited_year:
        try:
            dy = abs(int(stored_year) - int(cited_year))
            if dy > 1:
                layer2_ok = False
        except (TypeError, ValueError):
            layer2_ok = True

    if layer2_ok:
        trace.append("L2:PASS — court/year consistent or not provided")
    else:
        trace.append("L2:WARN — court/year mismatch (floors to YELLOW)")

    # ── LAYER 3: proposition alignment ───────────────────────────────────────
    score = max(0, min(100, base_score))

    # Cross-route bonus: if both Route 1 and 2 independently confirmed
    if (audit_info or {}).get("multi_route_confirmed"):
        score = min(100, score + 7)
        trace.append("L3:BONUS — confirmed by Route 1 and 2 (+7)")

    # Court-tier thresholds (score scaled 0–100 as per spec)
    if tier == "SC":
        green_t, yellow_t = 80, 75
    elif tier == "HC_MAJOR":
        green_t, yellow_t = 78, 73
    elif tier == "HC_OTHER":
        green_t, yellow_t = 75, 70
    elif tier == "DISTRICT":
        green_t, yellow_t = 90, 85
    else:
        green_t, yellow_t = 78, 73

    if score >= green_t and layer2_ok:
        status = "GREEN"
        verdict = "MATCH"
        trace.append(f"L3:PASS — score={score} ≥ {green_t} (GREEN)")
    elif score >= yellow_t:
        status = "YELLOW"
        verdict = "PARTIAL"
        trace.append(f"L3:WARN — score={score} in YELLOW band")
    else:
        status = "RED"
        verdict = "MISMATCH"
        trace.append(f"L3:FAIL — score={score} below RED threshold")

    # Layer 2 partial fail floors GREEN → YELLOW
    if status == "GREEN" and not layer2_ok:
        status = "YELLOW"
        trace.append("FLOOR:GREEN→YELLOW due to metadata mismatch")

    # Auditor QUARANTINED always forces RED (or PENDING for google-sourced)
    if str(audit_status or "").upper() == "QUARANTINED":
        # Web-only (google) citations that are quarantined go to PENDING queue
        # rather than hard RED — they were found on the web but not yet confirmed
        if route in ("google",) and score >= 30:
            status = "PENDING"
            trace.append("AUDITOR:QUARANTINED → PENDING (web-found, awaiting HITL confirmation)")
        else:
            status = "RED"
            trace.append("AUDITOR:QUARANTINED → force RED")

    # Confidence band for UI (50–99)
    confidence = min(99, max(50, score))
    return {
        "status": status,
        "confidence": confidence,
        "match_score": score,
        "verdict": verdict,
        "trace": trace,
        "route": route,
    }


# ─── Map judgement → citation object ─────────────────────────────────────────

def _judgement_to_citation(
    j: Dict[str, Any],
    index: int,
    query: str,
    audit_info: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """Map DB judgement row to one citation object in frontend format (all 10 fields)."""
    cid        = j.get("id") or str(uuid.uuid4())
    # Base source from ingestion pipeline (google / indian_kanoon / local / citation_agent)
    source_key = j.get("source", "unknown")
    # If auditor has stronger provenance (verified via local_db / IK), prefer that for display
    if audit_info:
        local_check = audit_info.get("local_check") or {}
        ik_check = audit_info.get("ik_check") or {}
        if local_check.get("verified"):
            source_key = "local"
        elif ik_check.get("verified"):
            source_key = "indian_kanoon"
    source_label = _SOURCE_LABELS.get(source_key, source_key.replace("_", " ").title())

    # Auditor status for logging / output
    audit_status = (audit_info or {}).get("audit_status") or j.get("audit_status")

    # Three-layer verification (existence, metadata, proposition alignment)
    v = _apply_three_layer_verification(j, query, source_key, audit_info)
    status = v["status"]
    confidence = v["confidence"]
    match_score = v["match_score"]
    verdict = v["verdict"]

    # Failure reason for RED / PENDING citations
    failure_reason = ""
    if status in ("RED", "PENDING"):
        failure_reason = _derive_failure_reason(j, audit_info, v)

    # Stale detection: citation was previously verified but has been overruled
    # Check overruledList from subsequent treatment AND last_verified_at age
    _st_raw = j.get("subsequent_treatment") or {}
    _overruled_raw = _st_raw.get("overruled") or []
    is_stale = False
    stale_reason = ""
    if status == "GREEN" and _overruled_raw:
        is_stale = True
        by = "; ".join(str(x) for x in _overruled_raw[:2])
        stale_reason = f"A later judgment may have affected this citation's validity. Possible overrule by: {by}"
        status = "STALE"  # downgrade GREEN to STALE for UI

    # Priority score for HITL queue ordering
    priority_score = _compute_priority_score(j, audit_info) if status in ("RED", "PENDING") else 0.0

    # Lists
    alt = j.get("alternate_citations") or []
    if isinstance(alt, str):
        try:   alt = json.loads(alt)
        except: alt = [x.strip() for x in alt.split(",") if x.strip()]
    alt = [str(x) for x in alt if x and str(x).strip() not in ("", "—")] if alt else []

    statutes = j.get("statutes") or []
    if isinstance(statutes, str):
        try:   statutes = json.loads(statutes)
        except: statutes = [x.strip() for x in statutes.split(";") if x.strip()]
    statutes = [str(s) for s in statutes if s and str(s).strip()] if statutes else []

    ratio        = (j.get("ratio") or "").strip()
    excerpt_text = _clean_excerpt((j.get("excerpt_text") or "").strip())
    excerpt_para = (j.get("excerpt_para") or "").strip()
    primary_cit = (j.get("primary_citation") or "").strip()
    paragraphs  = j.get("paragraphs") or []

    # Resolve pinpoint paragraph text from stored judgment paragraphs (from fetched judgment)
    if paragraphs and excerpt_para:
        para_num_match = re.search(r"para\s*(\d+)|paragraph\s*(\d+)|(\d+)", excerpt_para, re.I)
        if para_num_match:
            n = next((int(x) for x in para_num_match.groups() if x), 0)
            for p in paragraphs:
                pid = p.get("paragraph_id") if isinstance(p, dict) else getattr(p, "paragraph_id", None)
                if pid is not None and int(pid) == n:
                    text = p.get("text") if isinstance(p, dict) else getattr(p, "text", "")
                    if text:
                        excerpt_text = _clean_excerpt((text or "").strip()[:2000])
                    break
            else:
                # Try 0-based index
                if 0 <= n < len(paragraphs):
                    p = paragraphs[n]
                    text = p.get("text") if isinstance(p, dict) else getattr(p, "text", "")
                    if text:
                        excerpt_text = _clean_excerpt((text or "").strip()[:2000])
    # Sanitize: remove HTML/CSS so SOURCE EXCERPT shows only judgment text, not page styles
    sanitized = _clean_excerpt(excerpt_text)
    if sanitized:
        excerpt_text = sanitized
    # Fallback: use ratio as excerpt if excerpt_text blank or was stripped as CSS
    if not excerpt_text and ratio:
        excerpt_text = ratio[:400] + ("…" if len(ratio) > 400 else "")
    if not excerpt_text:
        raw_text = _clean_excerpt((j.get("raw_content") or j.get("full_text") or "").strip())
        if raw_text:
            excerpt_text = raw_text[:400] + ("..." if len(raw_text) > 400 else "")
    if not excerpt_para:
        excerpt_para = "Para 1"
    # Pinpoint citation: e.g. (1978) 1 SCC 248, para 7
    pinpoint_citation = ""
    if primary_cit and primary_cit not in ("—", "Further research needed"):
        pinpoint_citation = f"{primary_cit}, {excerpt_para}" if excerpt_para and excerpt_para != "—" else primary_cit

    # Subsequent treatment — Layer 1: Neo4j/DB data (from judgement_get)
    #                         Layer 2: text extraction from full judgment body
    st = j.get("subsequent_treatment") or {}
    followed_list = st.get("followed") or []
    distinguished_list = st.get("distinguished") or []
    overruled_list = st.get("overruled") or []

    # Layer 2: regex + LLM extraction from raw judgment body
    _full_text = (j.get("raw_content") or j.get("full_text") or ratio or "").strip()
    _case_title = j.get("title") or ""
    if _full_text:
        try:
            from subsequent_treatment_extractor import extract_subsequent_treatment_combined, merge_treatment
            # Combined = regex first, then Gemini LLM fills gaps
            _text_extracted = extract_subsequent_treatment_combined(_full_text, title=_case_title)
            _merged = merge_treatment(_text_extracted, st)
            followed_list      = _merged.get("followed", followed_list)
            distinguished_list = _merged.get("distinguished", distinguished_list)
            overruled_list     = _merged.get("overruled", overruled_list)
            # Expose full treatment detail for API response
            _treatment_detail = _merged.get("detail", {})
            _treatment_extra = {
                "reversed":    _merged.get("reversed", []),
                "relied_on":   _merged.get("relied_on", []),
                "applied":     _merged.get("applied", []),
                "cited":       _merged.get("cited", []),
                "referred":    _merged.get("referred", []),
                "approved":    _merged.get("approved", []),
                "detail":      _treatment_detail,
                "summary":     _merged.get("summary", {}),
            }
        except Exception as _te:
            logger.warning("[TREATMENT_EXTRACTOR] failed for %s: %s", cid, _te)
            _treatment_extra = {}
    else:
        _treatment_extra = {}

    followed = len(followed_list)
    distinguished = len(distinguished_list)
    overruled = len(overruled_list)

    treat_note = "Subsequent treatment data not yet indexed."
    if overruled_list:
        treat_note = "Overruled by: " + "; ".join(overruled_list[:3]) + (" …" if len(overruled_list) > 3 else "")
    elif followed_list or distinguished_list:
        parts = []
        if followed_list:
            parts.append("Followed in: " + "; ".join(followed_list[:2]))
        if distinguished_list:
            parts.append("Distinguished in: " + "; ".join(distinguished_list[:2]))
        treat_note = ". ".join(parts)
    elif ratio and (re.search(r"followed\s+in", ratio, re.I) or re.search(r"distinguished\s+in", ratio, re.I) or re.search(r"overruled", ratio, re.I)):
        treat_note = "See ratio for subsequent treatment references."

    # Official source link: prefer government/court URL, else fetcher URL
    official_source_url = j.get("official_source_url") or j.get("source_url") or "—"
    source_url = j.get("source_url") or j.get("official_source_url") or "—"
    verification_label = (
        j.get("verification_status_extracted")
        or (audit_info.get("audit_status") if audit_info else None)
        or "Requires review"
    )
    verification_label = str(verification_label or "Requires review").strip()
    if verification_label.upper() in ("VERIFIED", "VERIFIED_WITH_WARNINGS"):
        verification_label = "Verified and authentic"
    elif verification_label.upper() == "QUARANTINED":
        verification_label = "Invalid / not found"
    elif not verification_label or verification_label.upper() in ("NULL", "NONE", "NOT_AUDITED"):
        verification_label = "Requires review"

    source_icon = {"local": "🏛", "indian_kanoon": "📚", "google": "🌐"}.get(source_key, "🤖")
    # Explicit application name for UI: "Indian Kanoon", "Google Search", "Local DB" (not court)
    source_application = _SOURCE_LABELS.get(source_key) or source_label
    fetched_from_text = _SOURCE_FETCHED_FROM.get(source_key) or f"This relevant case was fetched from: {source_label}."
    import_link = j.get("import_source_link") or source_url
    if (import_link or source_url) and (import_link or source_url) != "—":
        fetched_from_text += f" URL: {import_link or source_url}"
    # Data complete when key fields are present and not placeholders
    case_name_ok = (j.get("title") or "").strip() and (j.get("title") or "").strip() not in (
        "—", "Unknown Case", "Further research needed", "Judgment", "Case name not found in the provided text.",
        "Not available in the provided text.",
    )
    citation_ok = (j.get("primary_citation") or "").strip() and (j.get("primary_citation") or "").strip() not in ("—", "Further research needed")
    ratio_ok = (ratio or "").strip() and (ratio or "").strip() not in ("Further research needed.", "Ratio not available.", "Ratio decidendi not available.")
    data_complete = bool(case_name_ok and citation_ok and ratio_ok)
    logger.info(
        "[REPORT_BUILDER] %s [%-14s] #%03d | %-40s | %s | conf=%d complete=%s",
        source_icon, source_key.upper(), index,
        (j.get("primary_citation") or "—")[:40],
        status, confidence, data_complete,
    )

    # Never show placeholder strings as case name (zero mistakes)
    case_name = (j.get("title") or "").strip()
    if not case_name or case_name.lower() in (
        "case name not found in the provided text.",
        "not available in the provided text.",
        "further research needed",
        "unknown case",
        "—",
        "judgment",
    ):
        case_name = primary_cit if primary_cit and primary_cit not in ("—", "Further research needed") else "Unknown Case"
    return {
        "id":                    f"cit-{index:03d}",
        "verificationStatus":    status,
        "verificationStatusLabel": verification_label,
        "confidence":            confidence,
        "caseName":              case_name,
        "primaryCitation":       j.get("primary_citation") or "—",
        "sourceApplication":     source_application,
        "dataComplete":          data_complete,
        "alternateCitations":    alt or [],
        "pinpointCitation":      pinpoint_citation or (j.get("primary_citation") or "—"),
        "court":                 j.get("court") or "Court not specified",
        "coram":                 j.get("coram") or "—",
        "benchType":             j.get("bench_type") or "—",
        "dateOfJudgment":        j.get("date_judgment") or "—",
        "statutes":              statutes if statutes else [],
        "ratio":                 ratio or "Ratio decidendi not available.",
        "proposition": {
            "query":      query,
            "matchScore": match_score,
            "verdict":    verdict,
        },
        "excerpt":               {"para": excerpt_para, "text": excerpt_text or ratio[:400] or "—"},
        "treatment": {
            "followed":         followed,
            "distinguished":    distinguished,
            "overruled":        overruled,
            "followedList":     followed_list[:10],
            "distinguishedList":distinguished_list[:10],
            "overruledList":    overruled_list[:5],
            "reversedList":     _treatment_extra.get("reversed", [])[:5],
            "reliedOnList":     _treatment_extra.get("relied_on", [])[:10],
            "appliedList":      _treatment_extra.get("applied", [])[:10],
            "citedList":        _treatment_extra.get("cited", [])[:10],
            "referredList":     _treatment_extra.get("referred", [])[:10],
            "approvedList":     _treatment_extra.get("approved", [])[:5],
            "detail":           _treatment_extra.get("detail", {}),
            "summary":          _treatment_extra.get("summary", {}),
            "note":             treat_note,
        },
        "sourceUrl":             source_url,
        "officialSourceLink":    official_source_url,
        "importSourceLink":      j.get("import_source_link") or source_url or official_source_url,
        "canonicalId":           j.get("canonical_id") or cid,
        "refreshed":             (j.get("refreshed_at") or datetime.utcnow().strftime("%d %b %Y"))[:12],
        "source":                source_key,
        "sourceLabel":           source_label,
        "sourceApplication":     source_application,
        "dataComplete":          data_complete,
        "fetchedFrom":           fetched_from_text,
        "auditStatus":           audit_status or j.get("audit_status") or "not_audited",
        "librarianStatus":       j.get("librarian_status") or "not_validated",
        "issue":                 j.get("issue") or query[:200] if query else "—",
        "relevanceToCurrentCase": j.get("relevance_to_current_case") or (ratio[:300] + "…" if len(ratio or "") > 300 else (ratio or "—")),
        "storedInEs":            j.get("canonical_id") or j.get("es_doc_id") or cid,
        "verificationRoute":     v.get("route"),
        "verificationTrace":     v.get("trace") or [],
        # 4-type unverified system
        "failureReason":         failure_reason,
        "isStale":               is_stale,
        "staleReason":           stale_reason,
        "priorityScore":         priority_score,
        "hitlTicketId":          None,  # filled by caller after HITL insert
    }


# ─── Text report (spec format) ─────────────────────────────────────────────────

def _build_text_report(
    citations: List[Dict[str, Any]],
    query: str,
    query_display: Optional[str] = None,
    search_keywords_by_route: Optional[Dict[str, List[str]]] = None,
) -> str:
    """Build optional text/markdown report: all 10 CITATION POINTs with Issue, Holding, Ratio, Relevance, Source (where fetched from), Stored in ES."""
    search_keywords_by_route = search_keywords_by_route or {}
    route_local = ", ".join(search_keywords_by_route.get("local") or [])
    route_ik = ", ".join(search_keywords_by_route.get("indian_kanoon") or [])
    route_google = ", ".join(search_keywords_by_route.get("google") or [])
    lines = [
        "CITATION REPORT",
        f"Query: {(query_display or query)[:200]}",
        f"Route 1 (Local DB) keywords: {route_local or '—'}",
        f"Route 2 (Indian Kanoon) keywords: {route_ik or '—'}",
        f"Route 3 (Google) keywords: {route_google or '—'}",
        f"Generated: {datetime.utcnow().strftime('%d %B %Y')}",
        f"Total citation points: {len(citations)}",
        "",
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
    ]
    for i, c in enumerate(citations, 1):
        lines.append(f"CITATION POINT {i} of {len(citations)}")
        lines.append(f"2.1 Case Name: {c.get('caseName') or '—'}")
        lines.append(f"2.2 Recognized Reporter Citation: {c.get('primaryCitation') or '—'} | Equivalents: {', '.join(c.get('alternateCitations') or []) or '—'}")
        lines.append(f"2.3 Court: {c.get('court') or '—'}")
        lines.append(f"2.4 Bench (Coram): {c.get('coram') or '—'} | {c.get('benchType') or '—'}")
        lines.append(f"2.5 Date of Judgment: {c.get('dateOfJudgment') or '—'}")
        lines.append(f"2.6 Ratio Decidendi: {c.get('ratio') or '—'}")
        exc = c.get("excerpt") or {}
        lines.append(f"2.7 Pinpoint Citation: {c.get('pinpointCitation') or c.get('primaryCitation') or '—'}")
        lines.append(f"    Source Excerpt ({exc.get('para') or 'Para'}): {str(exc.get('text') or '—')[:400]}")
        treat = c.get("treatment") or {}
        lines.append(f"2.8 Subsequent Treatment: Followed={treat.get('followed', 0)} Distinguished={treat.get('distinguished', 0)} Overruled={treat.get('overruled', 0)} | {treat.get('note') or '—'}")
        lines.append(f"2.9 Verification: {c.get('verificationStatusLabel') or c.get('verificationStatus') or '—'}")
        lines.append(f"2.10 Official Source Link: {c.get('officialSourceLink') or c.get('sourceUrl') or '—'}")
        imp_link = c.get("importSourceLink") or c.get("sourceUrl") or c.get("officialSourceLink")
        if imp_link and str(imp_link).strip() not in ("—", ""):
            lines.append(f"Data imported from: {imp_link}")
        lines.append(f"Issue: {c.get('issue') or '—'}")
        lines.append(f"Relevance: {c.get('relevanceToCurrentCase') or '—'}")
        lines.append(f"Source (where fetched from): {c.get('fetchedFrom') or '—'}")
        lines.append(f"Stored in ES: {c.get('storedInEs') or '—'}")
        lines.append("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    return "\n".join(lines)


# ─── Main build function ──────────────────────────────────────────────────────

def build_report_from_judgements(
    judgement_ids: List[str],
    query: str,
    user_id: str,
    audit_details: Optional[Dict[str, Any]] = None,
    search_keywords: Optional[List[str]] = None,
    search_keywords_by_route: Optional[Dict[str, List[str]]] = None,
) -> Dict[str, Any]:
    """
    Load judgements from DB, enrich with Gemini when fields are blank,
    then build report_format = { citations: [...], generatedAt }.
    """
    from db.client import judgement_get

    audit_details = audit_details or {}
    search_keywords = search_keywords or []
    search_keywords_by_route = search_keywords_by_route or {}
    query_display = ", ".join(search_keywords) if search_keywords else query
    source_counts: Dict[str, int] = {}

    logger.info("╔══ REPORT BUILDER (%d citations) ════════════════════════╗", len(judgement_ids))

    def _process_one(args):
        i, jid = args
        j = judgement_get(jid)
        if not j:
            logger.warning("  [SKIP] %s not in DB", jid)
            return None
        src = j.get("source", "unknown")
        source_counts[src] = source_counts.get(src, 0) + 1

        # Enrich missing fields via Gemini (parallel-safe, each call is independent)
        j = _enrich_with_gemini(j, query)

        audit_info = audit_details.get(jid)
        return _judgement_to_citation(j, i + 1, query, audit_info=audit_info)

    citations = []
    # Use thread pool to run Gemini enrichment + mapping in parallel
    with ThreadPoolExecutor(max_workers=min(6, max(len(judgement_ids), 1))) as pool:
        futures = {pool.submit(_process_one, (i, jid)): jid
                   for i, jid in enumerate(judgement_ids)}
        results_map = {}
        for fut in futures:
            try:
                cit = fut.result(timeout=60)
                if cit:
                    results_map[futures[fut]] = cit
            except Exception as e:
                logger.warning("  [ERROR] citation processing failed: %s", e)

    # Preserve original ordering; include every approved citation (all points in report)
    for jid in judgement_ids:
        cit = results_map.get(jid)
        if cit:
            citations.append(cit)

    # Sort so citations with complete data (case name + citation + ratio) come first, then by confidence
    citations.sort(key=lambda c: (not c.get("dataComplete", False), -(c.get("confidence") or 0)))

    # Fill up to TARGET_CITATION_POINTS (10) so report always has exactly 10 citation points
    while len(citations) < TARGET_CITATION_POINTS:
        n = len(citations) + 1
        citations.append({
            "id":                       f"cit-{n:03d}",
            "verificationStatus":       "YELLOW",
            "verificationStatusLabel":  "Requires review",
            "confidence":               50,
            "caseName":                 "Further research needed",
            "primaryCitation":          "—",
            "alternateCitations":       [],
            "pinpointCitation":         "—",
            "court":                    "—",
            "coram":                    "—",
            "benchType":                "—",
            "dateOfJudgment":           "—",
            "statutes":                 [],
            "ratio":                    "Further research needed.",
            "proposition":              {"query": query_display, "matchScore": 50, "verdict": "PARTIAL"},
            "excerpt":                  {"para": "—", "text": "—"},
            "treatment":                {"followed": 0, "distinguished": 0, "overruled": 0, "followedList": [], "distinguishedList": [], "overruledList": [], "note": "Subsequent treatment data not yet indexed."},
            "sourceUrl":                "—",
            "officialSourceLink":       "—",
            "canonicalId":              f"placeholder_{n}",
            "refreshed":                datetime.utcnow().strftime("%d %b %Y"),
            "source":                  "placeholder",
            "sourceLabel":              "Placeholder",
            "sourceApplication":       "—",
            "dataComplete":             False,
            "fetchedFrom":              "This citation point could not be filled; further research needed.",
            "auditStatus":              "NEEDS_REVIEW",
            "librarianStatus":          "not_validated",
            "issue":                    query[:200] if query else "—",
            "relevanceToCurrentCase":   "—",
            "storedInEs":               None,
        })

    # Renumber after ordering
    for i, cit in enumerate(citations):
        cit["id"] = f"cit-{i+1:03d}"

    logger.info("╠══ SOURCE DISTRIBUTION ═══════════════════════════════════╣")
    for src, cnt in sorted(source_counts.items()):
        icon = {"local": "🏛", "indian_kanoon": "📚", "google": "🌐"}.get(src, "🤖")
        logger.info("║  %s %-18s : %d", icon, src, cnt)
    logger.info("╚══════════════════════════════════════════════════════════╝")

    result = {
        "citations":       citations,
        "generatedAt":     datetime.utcnow().strftime("%d %B %Y"),
        "sourceBreakdown": source_counts,
        "totalPoints":     len(citations),
        "searchKeywords":  search_keywords,
        "searchKeywordsByRoute": search_keywords_by_route,
        "searchQuery":     query_display,
        "reportNote":      (
            f"This report contains {len(citations)} citation point(s) (target 10). "
            "Each point shows where that relevant case was fetched from: Indian Kanoon, Google Search, or Local DB (see 'fetchedFrom' / 'sourceLabel' per citation)."
        ),
    }
    # Optional text/markdown report format (all 10 points with Issue, Holding, Ratio, Source where fetched)
    result["textReport"] = _build_text_report(citations, query, query_display, search_keywords_by_route)
    return result
