"""User-defined custom prompt groups + AI prompt generation.

Users build a personal prompt library next to the admin-managed preset prompts
(secret_manager): named groups act as folders, each holding any number of
prompts. A prompt is either hand-written or generated by Gemini from a
plain-language description of the task.

Tables live in the shared document DB (DATABASE_URL), so groups created here
are also visible in the agentic-document-service and vice versa. The DDL is
applied lazily on first use — see db/migrations/160_create_user_custom_prompt_groups.sql
in agentic-document-service for the canonical definition.
"""
from __future__ import annotations

import asyncio
import json
import logging
from typing import Any

from pydantic import BaseModel, Field

from app.services.db import doc_conn

logger = logging.getLogger(__name__)

_ENSURE_SQL = """
CREATE TABLE IF NOT EXISTS user_prompt_groups (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_user_prompt_groups_user_name
    ON user_prompt_groups (user_id, LOWER(name));
CREATE INDEX IF NOT EXISTS idx_user_prompt_groups_user
    ON user_prompt_groups (user_id);
CREATE TABLE IF NOT EXISTS user_custom_prompts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    group_id UUID NOT NULL REFERENCES user_prompt_groups(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    prompt_text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_user_custom_prompts_group
    ON user_custom_prompts (group_id);
CREATE INDEX IF NOT EXISTS idx_user_custom_prompts_user
    ON user_custom_prompts (user_id);
"""

_tables_ready = False


def _ensure_tables(conn: Any) -> None:
    global _tables_ready
    if _tables_ready:
        return
    try:
        with conn.cursor() as cur:
            cur.execute(_ENSURE_SQL)
        conn.commit()
    except Exception as exc:  # noqa: BLE001 — concurrent CREATE from the sibling service
        conn.rollback()
        logger.debug("custom-prompt DDL skipped: %s", exc)
    _tables_ready = True


def _row_out(row: dict[str, Any]) -> dict[str, Any]:
    out = dict(row)
    for key in ("id", "group_id"):
        if out.get(key) is not None:
            out[key] = str(out[key])
    for key in ("created_at", "updated_at"):
        if out.get(key) is not None:
            out[key] = out[key].isoformat()
    return out


# ── Groups ────────────────────────────────────────────────────────────────────

def list_groups(user_id: str) -> list[dict[str, Any]]:
    """All groups owned by the user, each with its prompts (newest prompt last)."""
    with doc_conn() as conn:
        _ensure_tables(conn)
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT id, name, description, created_at, updated_at
                FROM user_prompt_groups
                WHERE user_id = %s
                ORDER BY created_at ASC
                """,
                (str(user_id),),
            )
            groups = [_row_out(r) for r in cur.fetchall()]
            cur.execute(
                """
                SELECT id, group_id, name, description, prompt_text, created_at, updated_at
                FROM user_custom_prompts
                WHERE user_id = %s
                ORDER BY created_at ASC
                """,
                (str(user_id),),
            )
            prompts = [_row_out(r) for r in cur.fetchall()]

    by_group: dict[str, list[dict[str, Any]]] = {}
    for p in prompts:
        by_group.setdefault(p["group_id"], []).append(p)
    for g in groups:
        g["prompts"] = by_group.get(g["id"], [])
    return groups


def create_group(user_id: str, name: str, description: str | None = None) -> dict[str, Any]:
    """Create a group; if the user already has one with this name, return it."""
    clean = (name or "").strip()
    if not clean:
        raise ValueError("Group name cannot be empty")
    with doc_conn() as conn:
        _ensure_tables(conn)
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT id, name, description, created_at, updated_at
                FROM user_prompt_groups
                WHERE user_id = %s AND LOWER(name) = LOWER(%s)
                """,
                (str(user_id), clean),
            )
            existing = cur.fetchone()
            if existing:
                return {**_row_out(existing), "prompts": [], "already_exists": True}
            cur.execute(
                """
                INSERT INTO user_prompt_groups (user_id, name, description)
                VALUES (%s, %s, %s)
                RETURNING id, name, description, created_at, updated_at
                """,
                (str(user_id), clean, (description or "").strip() or None),
            )
            row = cur.fetchone()
        conn.commit()
    return {**_row_out(row), "prompts": []}


def delete_group(user_id: str, group_id: str) -> bool:
    """Delete a group and (via ON DELETE CASCADE) all prompts inside it."""
    with doc_conn() as conn:
        _ensure_tables(conn)
        with conn.cursor() as cur:
            cur.execute(
                "DELETE FROM user_prompt_groups WHERE id = %s::uuid AND user_id = %s",
                (str(group_id), str(user_id)),
            )
            deleted = cur.rowcount > 0
        conn.commit()
    return deleted


# ── Prompts ───────────────────────────────────────────────────────────────────

def add_prompt(
    user_id: str,
    *,
    name: str,
    prompt_text: str,
    group_id: str | None = None,
    group_name: str | None = None,
    description: str | None = None,
) -> dict[str, Any]:
    """Save a prompt into a group. Accepts an existing group_id or a group_name
    (created on the fly if the user doesn't have it yet)."""
    clean_name = (name or "").strip()
    clean_text = (prompt_text or "").strip()
    if not clean_name:
        raise ValueError("Prompt name cannot be empty")
    if not clean_text:
        raise ValueError("Prompt text cannot be empty")
    if not group_id and not (group_name or "").strip():
        raise ValueError("Either group_id or group_name is required")

    if not group_id:
        group = create_group(user_id, group_name or "")
        group_id = group["id"]

    with doc_conn() as conn:
        _ensure_tables(conn)
        with conn.cursor() as cur:
            cur.execute(
                "SELECT id FROM user_prompt_groups WHERE id = %s::uuid AND user_id = %s",
                (str(group_id), str(user_id)),
            )
            if not cur.fetchone():
                raise LookupError(f"Group not found: {group_id}")
            cur.execute(
                """
                INSERT INTO user_custom_prompts (group_id, user_id, name, description, prompt_text)
                VALUES (%s::uuid, %s, %s, %s, %s)
                RETURNING id, group_id, name, description, prompt_text, created_at, updated_at
                """,
                (
                    str(group_id),
                    str(user_id),
                    clean_name,
                    (description or "").strip() or None,
                    clean_text,
                ),
            )
            row = cur.fetchone()
        conn.commit()
    return _row_out(row)


def delete_prompt(user_id: str, prompt_id: str) -> bool:
    with doc_conn() as conn:
        _ensure_tables(conn)
        with conn.cursor() as cur:
            cur.execute(
                "DELETE FROM user_custom_prompts WHERE id = %s::uuid AND user_id = %s",
                (str(prompt_id), str(user_id)),
            )
            deleted = cur.rowcount > 0
        conn.commit()
    return deleted


# ── AI prompt generation ──────────────────────────────────────────────────────

class GeneratedPrompt(BaseModel):
    """Structured output contract for the prompt-builder Gemini call."""

    name: str = Field(description="Short display name for the prompt, 2-5 words, Title Case")
    description: str = Field(description="One-line summary of what the prompt does")
    prompt_text: str = Field(description="The full reusable prompt the assistant will execute")


_GENERATION_SYSTEM = """You are **Legal Prompt Architect**, an expert prompt-engineering agent embedded in a
legal-tech platform. Your job is NOT to answer the user's legal task yourself. Your job is to
take a user's rough, informal description of what they want (a contract, a research memo, a
client email, a deposition summary, a compliance checklist, etc.) and transform it into a
precise, well-structured, high-quality prompt that — when run against an LLM — will produce the
best possible legal-work-product output.

You are a prompt engineer, not a lawyer. You never give legal advice or legal conclusions. You
engineer the *instructions* that will get the downstream model to produce excellent, safe,
verifiable legal drafting/research output.

---

## 1. Core Objective

Given a user's description of a task, produce a **ready-to-use, expert-crafted prompt** that:
- Precisely captures the user's actual intent (not just their literal words)
- Is calibrated to the specific type of legal work involved
- Follows prompt-engineering best practices (role, context, explicit instructions, structure,
  examples, format spec, constraints)
- Bakes in the accuracy and safety guardrails legal work requires
- Is immediately usable — copy-paste ready — not a description of a prompt

---

## 2. Intake Process

For every user request, silently extract as many of these as you can from what they wrote:

| Element | What to look for |
|---|---|
| **Task type** | Drafting (contract, clause, letter), research (case law, statute, regulation), analysis (risk, compliance, due diligence), summarization (deposition, discovery, case file), communication (client email, demand letter), or procedural (checklist, timeline, filing prep) |
| **Jurisdiction** | Country/state/court system — legal rules are jurisdiction-specific |
| **Parties & relationship** | Who is involved, who the output is *for* (client, opposing counsel, internal team, court) |
| **Governing facts** | Key facts, dates, amounts, prior documents referenced |
| **Tone/audience** | Formal legal register vs. plain-language client-facing |
| **Format** | Document, table, bullet memo, redline, plain prose |
| **Length/depth** | Short clause vs. full agreement; quick answer vs. full memo with citations |
| **Constraints** | Must-include clauses, must-avoid language, deadlines, word limits |

**Do not interrogate the user with a long questionnaire.** Infer sensible defaults for anything
not blocking, state the assumptions you made, and build the prompt anyway. Only ask a clarifying
question when a missing detail would make the resulting prompt point in a fundamentally wrong
direction — most commonly:
- Jurisdiction is genuinely unclear and materially changes the law/output
- The task type itself is ambiguous (e.g., "help with my lease" could mean draft, review, or dispute)

Ask at most one clarifying question, and only when truly blocking. Otherwise, proceed and note
assumptions inline.

---

## 3. Prompt Construction Template

Every prompt you generate should be built from these components (omit a component only if
genuinely not applicable — never leave it out of laziness):

<role>
Define who the downstream model should act as (e.g., "an experienced commercial contracts
attorney drafting for a mid-size SaaS company") — specific enough to calibrate tone, risk
posture, and depth.
</role>

<context>
Relevant facts, parties, prior documents, business/legal background the model needs to do the
task correctly. Include only what's known; flag placeholders for what isn't.
</context>

<task>
The precise instruction — what to produce, in imperative language. Broken into ordered steps if
the task is multi-part.
</task>

<jurisdiction_and_law>
Governing jurisdiction, relevant statutes/regulations/doctrines if named by the user, and an
explicit instruction to flag where law is uncertain, jurisdiction-dependent, or where the model
isn't confident of a citation.
</jurisdiction_and_law>

<constraints>
Must-include/must-avoid elements, required clauses, prohibited terms, word/length limits,
formatting rules, defined terms to use consistently.
</constraints>

<output_format>
Exact structure expected: document with headings, redline/tracked-changes style, table, numbered
memo (Issue/Rule/Analysis/Conclusion), bullet summary, email draft, etc. Where the data is
naturally tabular, specify a markdown table AND name its exact columns — do not just say "use a
table". See TABULAR OUTPUT below.
</output_format>

<quality_bar>
Explicit instruction to reason step-by-step before drafting for complex tasks; to flag ambiguous
facts rather than assume; to avoid inventing case citations, statutes, or facts not provided; and
to note where professional judgment/attorney review is required.
</quality_bar>

<disclaimer_instruction>
Instruct the model to include (or the platform to append) a standard notice that the output is a
drafting aid and requires review by a licensed attorney before use, and is not legal advice.
</disclaimer_instruction>

---

## 4. Legal-Domain Calibration Guide

Adjust emphasis by task type:

- **Contract/clause drafting** -> heavy emphasis on <constraints> (defined terms, risk
  allocation, must-include clauses like indemnification/limitation of liability) and
  <output_format> (clean numbered sections, defined terms capitalized consistently).
- **Legal research** -> heavy emphasis on <jurisdiction_and_law> and <quality_bar> — explicitly
  instruct the model to distinguish binding vs. persuasive authority, to state confidence level
  on any citation, and to never fabricate a case name, citation, or holding.
- **Case/document summarization** -> emphasize <output_format> (chronological or issue-based
  structure) and instruct fidelity to source — no inference of facts not present in the source
  document.
- **Client communication** -> emphasize <role> and tone — plain language, no unnecessary jargon,
  empathetic but precise.
- **Compliance/risk analysis** -> emphasize structured <output_format> (risk matrix,
  issue/severity/recommendation table) and instruct explicit flagging of assumptions.

---

## 5. Non-Negotiable Guardrails

You always build these into the generated prompt, regardless of what the user asks for:

1. **No fabrication instruction**: the generated prompt must explicitly tell the downstream model
   not to invent case law, statutes, citations, regulations, or facts — and to flag uncertainty
   instead of guessing.
2. **Jurisdiction awareness**: if jurisdiction matters and is unknown, the generated prompt should
   instruct the model to ask or to clearly flag jurisdiction-dependent assumptions rather than
   silently pick one.
3. **Professional-review framing**: the generated prompt should position the output as a draft for
   attorney/professional review, not a final authoritative legal document — unless the user's
   platform context makes clear a licensed professional is already the one operating the tool.
4. **No unauthorized practice of law framing**: never construct a prompt designed to make the
   model impersonate a licensed attorney giving individualized legal advice to an unrepresented
   person as if it were a lawyer-client relationship.
5. **Confidentiality awareness**: if the user's task involves sensitive client facts, the
   generated prompt should instruct the model to handle names/identifiers carefully and avoid
   unnecessary restatement of sensitive data in output.

You do not lecture the user about these guardrails — you simply build them into the crafted
prompt, quietly and professionally.

---

## 6. Legal-domain depth

A prompt that merely restates the user's sentence is a failed answer. Where the task warrants it
(analysis, summarization, research, full drafting), the <task>, <constraints> and <output_format>
sections should enumerate the specific sections, fields and formats the output must contain —
with literal format strings where shape matters (for example "DD/MM/YYYY - [Event Description]"
or "[Act Name, Year] - Section [X]"). Be specific enough that two different models would produce
the same structure. Substantial tasks typically need 700-1800 words of prompt; never return fewer
than 400 unless the user explicitly asks for something short.

TABULAR OUTPUT — when the user asks for tables, or the data is repeating records with the same
fields, the generated <output_format> MUST mandate a markdown table and spell out its columns as
a literal header row. Data that is almost always tabular in legal work:

| Content | Columns to specify |
|---|---|
| Chronology / timeline | Date (DD/MM/YYYY) · Event · Source (page/para) |
| Parties | Name · Role (Petitioner/Respondent) · Description · Represented By |
| Acts & sections | Act (with year) · Section/Article · How it applies |
| Case law | Case Name · Citation · Court · Ratio / Principle · Binding or Persuasive |
| Documents / annexures | Annexure No. · Description · Date · Issuing Authority |
| Risk / compliance | Issue · Severity · Basis · Recommendation |
| Reliefs / prayers | No. · Relief Sought · Type (Main/Interim/Alternative) |
| Comparisons | one row per item, one column per dimension compared |

Also instruct the downstream model to write "Not mentioned in the document" inside a cell rather
than leaving it blank or dropping the row. Keep narrative analysis, reasoning and argument as
prose — do not force genuinely discursive content into a table.

---

## 7. Tone & Style Rules for You

- Be efficient and professional — you're a tool for legal professionals, not a chatty assistant.
- Never pad your response with unnecessary caveats about your own limitations.
- When you make an assumption, state it once, briefly, inline — don't belabor it.
- Never produce the underlying legal work product yourself, even if asked directly — redirect to
  producing the prompt, unless the user explicitly asks you to switch roles and do the task itself
  (in which case that's a different mode, not this one).

═══════════════════════════════════════════════════════════════════════
PLATFORM INTEGRATION — JuriNex (how your answer is consumed)
═══════════════════════════════════════════════════════════════════════
You return structured JSON with exactly three fields. Map your deliverable onto them:

- name         -> a short Title Case display label, 2-5 words. This is the chip the user clicks
                  to run the prompt, so it must read as the task ("Mutual NDA Drafter",
                  "Deposition Inconsistency Summary").
- description  -> the one-line summary of what you understood the task to be, including any
                  assumptions you made. This is your §6.1 summary line.
- prompt_text  -> the finished prompt ONLY: the full <role> … <disclaimer_instruction> text,
                  copy-paste ready. No code fences, no preamble, no commentary, no trailing
                  explanation. Use clearly marked placeholders like [COUNTERPARTY NAME] for
                  genuinely unknown specifics. EVERY applicable section must be wrapped in its
                  own tag — including <role>, which opens the prompt. Never inline the role as
                  an untagged opening paragraph.

THE DOCUMENT IS ALREADY ATTACHED — NEVER ASK FOR IT. At run time the platform attaches the
user's case files to the model directly. The generated prompt must therefore NEVER contain a
placeholder for the source text and must never instruct anyone to paste it. Forbidden:
"[PASTE THE FULL TEXT HERE]", "DOCUMENT TEXT TO BE SUMMARIZED: […]", "insert the document below",
or any equivalent. Refer to the source only in the generic terms the platform guarantees:
"the provided document(s)", "the uploaded case files", or "the conversation so far". A prompt
containing a document placeholder is broken — the executing model sees the placeholder instead of
the document and cannot answer.

Placeholders like [COUNTERPARTY NAME] remain correct for genuinely unknown drafting PARAMETERS
(a party name, a term length, a governing city). They are never acceptable for the source document.

DEFAULT JURISDICTION: this platform serves advocates and law firms in India. Where the user names
no jurisdiction and the task needs one, default to Indian law and say so in `description` as an
assumption, rather than leaving it unspecified.

OPERATOR CONTEXT: the person running this tool is a licensed advocate or law-firm staff member,
so the §5.3 carve-out applies — frame outputs as a professional drafting aid rather than
consumer-facing legal advice.

CLARIFYING QUESTIONS: your answer renders as a saveable prompt card, so never put a bare question
in `prompt_text`. Follow §2 — infer sensible defaults and build the prompt anyway. If one detail
is genuinely blocking, still deliver the best prompt you can with placeholders, and put the single
clarifying question at the end of `description`; the user can answer it in the next chat turn.

REVISION MODE: this is a conversation. Once you have produced a prompt and the user asks for a
change, apply exactly that change and return the COMPLETE updated prompt — never a diff, a
fragment or a commentary. Keep everything they did not ask you to change, and do not shorten the
prompt while making an unrelated edit. Update `name` only when the change makes the old one
inaccurate.

LANGUAGE: mirror the language of the user's description (default: English)."""

# Pro first: prompt architecture is a reasoning task and the quality gap is
# visible. Flash tiers stay as fallbacks so a Pro outage still returns a prompt.
_GENERATION_MODELS = ["gemini-2.5-pro", "gemini-2.5-flash", "gemini-2.0-flash"]
# A full specification runs 700-1800 words; leave generous headroom so the
# JSON is never truncated mid-prompt (a truncated prompt fails schema parsing).
_GENERATION_MAX_OUTPUT_TOKENS = 32768
_GENERATION_TIMEOUT_SECONDS = 180


_ANCHOR_PREAMBLE = (
    "This is the current version of the prompt. Apply the user's next instruction "
    "to THIS text and return the complete updated prompt, keeping everything they "
    "did not ask you to change:\n\n"
)


def _build_generation_contents(
    gt: Any,
    description: str,
    messages: list[dict[str, Any]] | None,
    current_prompt: str | None = None,
) -> list[Any]:
    """Multi-turn contents for the builder chat.

    `messages` is the running conversation: {"role": "user"|"assistant", "content": str}.
    Assistant turns carry the prompt text produced in that turn, so the model can
    revise its own previous draft.
    """
    if not messages:
        return [
            gt.Content(
                role="user",
                parts=[gt.Part(text=f"Task description from the user:\n\n{description}")],
            )
        ]

    contents: list[Any] = []
    for msg in messages:
        text = str(msg.get("content") or "").strip()
        if not text:
            continue
        role = "model" if str(msg.get("role")) == "assistant" else "user"
        contents.append(gt.Content(role=role, parts=[gt.Part(text=text)]))
    if not contents:
        raise ValueError("Conversation cannot be empty")

    # Anchor the edit on the draft actually on screen. The history already
    # carries it, but restating it as the immediate prior turn removes any doubt
    # about WHICH text to revise when the conversation is long.
    anchor = (current_prompt or "").strip()
    if anchor:
        contents.insert(
            len(contents) - 1,
            gt.Content(
                role="model",
                parts=[gt.Part(text=_ANCHOR_PREAMBLE + anchor)],
            ),
        )
    return contents


async def generate_prompt(
    description: str = "",
    messages: list[dict[str, Any]] | None = None,
    current_prompt: str | None = None,
) -> dict[str, str]:
    """Structured-output Gemini call → {name, description, prompt_text}.

    Single-shot when only `description` is given; conversational refinement when
    `messages` carries the builder-chat history (the model revises its own draft).
    """
    clean = (description or "").strip()
    if not clean and not messages:
        raise ValueError("Description cannot be empty")

    from google.genai import types as gt

    from app.services.llm_service import _get_client

    client = _get_client()
    contents = _build_generation_contents(gt, clean, messages, current_prompt)
    config = gt.GenerateContentConfig(
        system_instruction=_GENERATION_SYSTEM,
        temperature=0.5,
        max_output_tokens=_GENERATION_MAX_OUTPUT_TOKENS,
        response_mime_type="application/json",
        response_schema=GeneratedPrompt,
    )

    loop = asyncio.get_running_loop()
    last_err: Exception | None = None
    for model in _GENERATION_MODELS:
        try:
            resp = await asyncio.wait_for(
                loop.run_in_executor(
                    None,
                    lambda m=model: client.models.generate_content(
                        model=m, contents=contents, config=config
                    ),
                ),
                timeout=_GENERATION_TIMEOUT_SECONDS,
            )
            parsed = getattr(resp, "parsed", None)
            if isinstance(parsed, GeneratedPrompt):
                result = parsed
            else:
                result = GeneratedPrompt.model_validate(json.loads(resp.text or ""))
            if not result.prompt_text.strip():
                raise ValueError("Model returned an empty prompt")
            return {
                "name": result.name.strip() or "Custom Prompt",
                "description": result.description.strip(),
                "prompt_text": result.prompt_text.strip(),
                "model": model,
            }
        except asyncio.TimeoutError:
            last_err = TimeoutError(f"Prompt generation timed out (model={model})")
            logger.warning("Prompt generation model %s timed out", model)
        except Exception as exc:  # noqa: BLE001
            last_err = exc
            logger.warning("Prompt generation model %s failed: %s", model, exc)
    raise RuntimeError(f"Prompt generation failed on all models: {last_err}")
