import React, { useCallback, useEffect, useRef, useState } from 'react';
import { renderAsync } from 'docx-preview';

/**
 * Renders a .docx in the "Original Document" panel.
 *
 * The viewer is given a signed URL to the raw upload, and a browser cannot display a .docx: pointing an
 * iframe at one makes the browser treat it as a download, which both left the panel blank and silently
 * downloaded the file just for opening the preview. docx-preview parses the OOXML in the browser, so the
 * file is rendered rather than navigated to.
 *
 * `renderAsync` takes binary data, never a URL, so the file is fetched into a Blob first. That is the
 * same plain GET pdf.js already makes against these signed URLs.
 */

// Prefixes every selector docx-preview generates (`.jrx-docx-wrapper`, `section.jrx-docx`, ...). The
// library injects real <style> elements, which apply document-wide no matter which container they are
// appended to — this prefix is the only thing keeping the document's styles off the app's markup, so it
// must stay a name the app itself would never use. The default is the far likelier "docx".
const DOCX_CLASS = 'jrx-docx';

const DOCX_OPTIONS = {
  className: DOCX_CLASS,
  // Keeps generated CSS custom properties under `.jrx-docx-wrapper`. With `inWrapper: false` they are
  // written onto the global `:root` instead.
  inWrapper: true,
  // Word records where it broke pages; honouring those hints keeps the page split close to the real
  // document. Defaults to true (ignore), which collapses a document into one tall page. Documents with
  // no such hints (e.g. generated by a script) still render as a single page — there is no reflow engine
  // here, so pages come from recorded breaks only.
  ignoreLastRenderedPageBreak: false,
  renderHeaders: true,
  renderFooters: true,
  // Embedded fonts are kept for fidelity — this panel is the reference the OCR output is checked
  // against. The cost: @font-face rules are global by nature and the class prefix above does NOT cover
  // them, so a document embedding a font named like one of the app's own would shadow it. Bounded to
  // while the modal is open (the <style> elements live in this panel and die with it). Set
  // `ignoreFonts: true` to trade the fidelity away if that ever bites.
  ignoreFonts: false,
};

export interface DocxPanelProps {
  url: string | null;
  zoom: number;
  onDownload?: () => void;
}

const DocxPanel: React.FC<DocxPanelProps> = ({ url, zoom, onDownload }) => {
  const bodyRef = useRef<HTMLDivElement | null>(null);
  const styleRef = useRef<HTMLDivElement | null>(null);
  const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading');
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  const baseUrl = url ? url.split('#')[0] : null;

  useEffect(() => {
    if (!baseUrl) return;

    // The fetch and the parse both resolve after an await, by which point the panel may be gone or
    // pointed at another file. Rendering then would write into a stale container.
    let cancelled = false;

    setStatus('loading');
    setErrorMessage(null);

    const render = async () => {
      try {
        const response = await fetch(baseUrl);
        if (!response.ok) {
          throw new Error(`Fetch failed with HTTP ${response.status}`);
        }
        const blob = await response.blob();
        if (cancelled) return;

        const body = bodyRef.current;
        const styles = styleRef.current;
        // Both containers mount unconditionally, so this should be unreachable — but returning here
        // without a status would leave the panel spinning forever.
        if (!body || !styles) {
          throw new Error('Preview container was not available');
        }

        // Both containers are emptied by renderAsync on every call, so they must be elements this panel
        // owns. Passing document.head as the style container would erase the whole head.
        await renderAsync(blob, body, styles, DOCX_OPTIONS);
        if (cancelled) return;
        setStatus('ready');
      } catch (err: any) {
        if (cancelled) return;
        console.warn('[OCR PREVIEW] docx render failed:', err);
        setErrorMessage(err?.message || 'Unknown error');
        setStatus('error');
      }
    };

    render();
    return () => {
      cancelled = true;
    };
  }, [baseUrl]);

  const header = (
    <h3 className="text-sm font-semibold text-gray-900 shrink-0">
      Original Document{status === 'ready' ? ` (${Math.round(zoom * 100)}%)` : ''}
    </h3>
  );

  if (!baseUrl) {
    return (
      <div className="flex flex-col h-full min-h-0 gap-3">
        {header}
        <div className="flex-1 flex items-center justify-center text-gray-500 text-sm bg-gray-50 rounded-lg border border-gray-200">
          Original file preview unavailable
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full min-h-0 gap-3">
      {header}
      <div className="jrx-docx-panel flex-1 min-h-0 rounded-lg border border-gray-200 bg-gray-100 overflow-auto relative">
        {/* Two classes beat docx-preview's own single-class rules regardless of which <style> the
            browser sees first, so the library's gray page-viewer chrome cannot override this. */}
        <style>{`
          .jrx-docx-panel .${DOCX_CLASS}-wrapper {
            background: transparent;
            padding: 8px;
            gap: 8px;
          }
          .jrx-docx-panel .${DOCX_CLASS}-wrapper > section.${DOCX_CLASS} {
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12);
            margin-bottom: 0;
          }
        `}</style>

        {status === 'loading' && (
          <div className="absolute inset-0 flex items-center justify-center text-sm text-gray-500 bg-gray-100 z-10">
            Loading document…
          </div>
        )}

        {status === 'error' && (
          <div className="absolute inset-0 flex flex-col items-center justify-center gap-3 px-6 text-center bg-gray-50 z-10">
            <div>
              <p className="text-sm font-medium text-gray-700 mb-1">
                Could not display this Word document
              </p>
              <p className="text-xs text-gray-500 max-w-md">
                {errorMessage}
              </p>
            </div>
            {onDownload && (
              <button
                type="button"
                onClick={onDownload}
                className="inline-flex items-center justify-center px-4 py-2 rounded-md text-sm font-medium text-white"
                style={{ backgroundColor: '#21C1B6' }}
              >
                Download original
              </button>
            )}
          </div>
        )}

        {/* `zoom` reflows the content, so the scrollbars stay correct; a transform would scale the
            painted output while leaving the scroll area at its unscaled size. */}
        <div style={{ zoom }}>
          <div ref={styleRef} />
          <div ref={bodyRef} />
        </div>
      </div>
    </div>
  );
};

export default DocxPanel;
